add reducers and actions
Daniel-Kigozi/react-book-store pull request #2
Opened 2023-05-09 13:56 UTC by Daniel-Kigozi

In this milestone, I did the following
- Add reducers and actions

2023-05-09 14:23 UTC, ichala requested changes
Hi Student
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No Linter errors  ✔️ 
- Created Book Slices ✔️


 ## Required Changes ♻️

- [ ] **_🛑 x_**
- [ ] **_🛑  Check The Comments Below_**





## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 14:23 UTC, ichala commented on src/redux/Categories/categories.js
> +export { checkStatus };
- [ ] as you did with the book reducer, kindly re-create the category reducer using `{ createSlice } from "@reduxjs/toolkit"` and add an initial state (it can be the empty string) , here's an example to guide you through it :

```javascript
import { createSlice } from "@reduxjs/toolkit"

export const categoriesSlice = createSlice({
  name: "categories",
  initialState: {
    categories: [],
  },
  reducers: {
    checkStatus: (state, action) => {
      state.categories =
        action.payload === "Under construction"
          ? "Under construction"
          : state.categories
    },
  },
})

export const { checkStatus } = categoriesSlice.actions

export default categoriesSlice.reducer
```

 🛑 Note : this is just an example kindly create your own code with your own variables name etc ...

2023-05-10 13:06 UTC, Ibizugbe approved these changes
Hi @Daniel-Kigozi 👋👋👋, 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Linters are properly setup and they are passing👍.
- [x] The catigories have been created using the `createSlice` method👍.

## Optional suggestions

_see comments below😊_

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 13:06 UTC, Ibizugbe commented on src/redux/Categories/categories.js
> +    addCategory: (state, action) => {
[OPTIONAL] The essence of this reducer is to check status as required😉 Hence, I will suggest you give the right name to make your codebase easily understandable 👍.

2023-05-10 14:01 UTC, merged